const int exerciseNameLength = 70;
const String dialogShowCancelButton = 'dialogShowCancelButton';
const bool dialogShowCancelButtonByDefault = true;
const String dialogSaveButtonName = 'dialogSaveButtonName';
const String dialogSaveButtonNameByDefault = 'Save';
const String textOK = 'OK';
const int lastRefreshToken = 2592000000;  // 30 days
const String allItems = 'allItems';
// const String urlAddressToSendRequests = 'http://localhost:3000';
const String urlAddressToSendRequests = 'https://loggerfit.herokuapp.com';